# Generated by Django 3.1.5 on 2021-01-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('ifsc', models.TextField(max_length=11, primary_key=True, serialize=False)),
                ('branch', models.TextField(max_length=74)),
                ('address', models.TextField(max_length=195)),
                ('city', models.TextField(max_length=50)),
                ('district', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=26)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restApi.banks')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
    ]
