# Generated by Django 3.1.5 on 2021-01-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_banks_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('capacity', models.IntegerField()),
                ('entryFee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isRunning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseChargeAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restApi.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='branches',
            name='bank',
        ),
        migrations.DeleteModel(
            name='banks',
        ),
        migrations.DeleteModel(
            name='branches',
        ),
        migrations.AddField(
            model_name='lottery',
            name='participants',
            field=models.ManyToManyField(related_name='lottery_participants', to='restApi.user'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lottery_winner_user', to='restApi.user'),
        ),
    ]
