# Generated by Django 3.1.5 on 2021-01-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_auto_20210123_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='houseChargeAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lottery_winner_user', to='restApi.user'),
        ),
    ]
