# Generated by Django 3.1.5 on 2021-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_auto_20210123_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='lottery_participants', to='restApi.user'),
        ),
    ]
