# Generated by Django 3.1.5 on 2021-01-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_auto_20210123_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='isRunning',
            new_name='finished',
        ),
    ]
